<a href="https://colab.research.google.com/github/jatavor1/MusicLikeability/blob/main/MusicPredictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split

In [6]:
from google.colab import drive

In [7]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [11]:
data = pd.read_csv('/content/drive/MyDrive/Data/Music.csv')

In [13]:
data.head()

Unnamed: 0  acousticness  danceability  duration_ms  energy  \
0           0        0.0102         0.833       204600   0.434   
1           1        0.1990         0.743       326933   0.359   
2           2        0.0344         0.838       185707   0.412   
3           3        0.6040         0.494       199413   0.338   
4           4        0.1800         0.678       392893   0.561   

   instrumentalness  key  liveness  loudness  mode  speechiness    tempo  \
0          0.021900    2    0.1650    -8.795     1       0.4310  150.062   
1          0.006110    1    0.1370   -10.401     1       0.0794  160.083   
2          0.000234    2    0.1590    -7.148     1       0.2890   75.044   
3          0.510000    5    0.0922   -15.236     1       0.0261   86.468   
4          0.512000    5    0.4390   -11.648     0       0.0694  174.004   

   time_signature  valence  target      song_title            artist  \
0               4    0.286       1        Mask Off            Future   
1               4    0.588       1         Redbone  Childish Gambino   
2               4    0.173       1    Xanny Family            Future   
3               4    0.230       1  Master Of None       Beach House   
4               4    0.904       1  Parallel Lines       Junior Boys   

   Likeability  
0          0.0  
1          1.0  
2          0.0  
3          0.0  
4          0.0

In [15]:
data.dtypes

Unnamed: 0            int64
acousticness        float64
danceability        float64
duration_ms           int64
energy              float64
instrumentalness    float64
key                   int64
liveness            float64
loudness            float64
mode                  int64
speechiness         float64
tempo               float64
time_signature        int64
valence             float64
target                int64
song_title           object
artist               object
Likeability         float64
dtype: object

In [29]:
import plotly.express as px
tList = data['Likeability'].unique()
for target in (tList):
    df = data[data['Likeability'] == 1.0]
    graph1 =  px.line(df , x = "Likeability", y = "tempo" , title = "Preferred")
    graph1.show()

In [30]:
tList = data['Likeability'].unique()
for target in (tList):
    df = data[data['Likeability'] == 0.0]
    graph2 = px.line(df , x = "Likeability", y = "tempo" , title = "Dont Like")
    graph2.show()

In [16]:
X = data.iloc[:,1:11].values
Y = data.iloc[:,17].values
print(X[0:5])
print(Y[0:5])

[[ 1.02000e-02  8.33000e-01  2.04600e+05  4.34000e-01  2.19000e-02
   2.00000e+00  1.65000e-01 -8.79500e+00  1.00000e+00  4.31000e-01]
 [ 1.99000e-01  7.43000e-01  3.26933e+05  3.59000e-01  6.11000e-03
   1.00000e+00  1.37000e-01 -1.04010e+01  1.00000e+00  7.94000e-02]
 [ 3.44000e-02  8.38000e-01  1.85707e+05  4.12000e-01  2.34000e-04
   2.00000e+00  1.59000e-01 -7.14800e+00  1.00000e+00  2.89000e-01]
 [ 6.04000e-01  4.94000e-01  1.99413e+05  3.38000e-01  5.10000e-01
   5.00000e+00  9.22000e-02 -1.52360e+01  1.00000e+00  2.61000e-02]
 [ 1.80000e-01  6.78000e-01  3.92893e+05  5.61000e-01  5.12000e-01
   5.00000e+00  4.39000e-01 -1.16480e+01  0.00000e+00  6.94000e-02]]
[0. 1. 0. 0. 0.]


In [17]:
print(X.shape)
print(Y.shape)

(2017, 10)
(2017,)


In [19]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y1 = encoder.fit_transform(Y)
print(y1)

[0 1 0 ... 0 0 0]


In [20]:
Y = pd.get_dummies(y1).values
print(Y[0:5])

[[1 0 0]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]


In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)
print(X_train[0:5])

[[ 4.56000e-01  5.14000e-01  2.15613e+05  4.53000e-01  1.81000e-04
   6.00000e+00  1.78000e-01 -7.06200e+00  1.00000e+00  2.67000e-02]
 [ 6.33000e-02  8.97000e-01  3.34467e+05  6.61000e-01  0.00000e+00
   8.00000e+00  1.16000e-01 -6.20000e+00  0.00000e+00  2.70000e-01]
 [ 8.95000e-01  4.44000e-01  1.51092e+05  4.12000e-01  6.40000e-01
   0.00000e+00  1.45000e-01 -1.15690e+01  1.00000e+00  4.65000e-02]
 [ 5.88000e-02  6.53000e-01  2.16613e+05  7.48000e-01  0.00000e+00
   1.00000e+01  1.94000e-01 -6.32300e+00  0.00000e+00  2.11000e-01]
 [ 6.77000e-02  5.87000e-01  1.80252e+05  6.28000e-01  1.88000e-06
   1.00000e+00  1.22000e-01 -5.70300e+00  1.00000e+00  4.31000e-02]]


In [22]:
print(Y_train[0:5])

[[1 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]]


In [23]:
print(X_test[0:5])
print(Y_test[0:5])

[[ 9.37000e-01  7.72000e-01  2.20093e+05  6.35000e-01  1.80000e-02
   0.00000e+00  9.61000e-02 -8.41200e+00  1.00000e+00  5.36000e-02]
 [ 9.85000e-02  6.47000e-01  2.77375e+05  8.41000e-01  0.00000e+00
   1.00000e+01  8.97000e-01 -2.50700e+00  1.00000e+00  1.64000e-01]
 [ 6.39000e-02  7.42000e-01  2.56693e+05  9.45000e-01  1.65000e-01
   5.00000e+00  1.31000e-01 -6.44500e+00  1.00000e+00  4.28000e-02]
 [ 6.24000e-04  9.06000e-01  3.11365e+05  6.48000e-01  8.57000e-02
   1.10000e+01  2.72000e-01 -8.74200e+00  0.00000e+00  7.34000e-02]
 [ 8.59000e-01  4.56000e-01  2.43013e+05  2.57000e-01  4.75000e-01
   1.00000e+01  1.11000e-01 -1.68770e+01  0.00000e+00  2.98000e-02]]
[[0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]]


In [24]:
model = tf.keras.Sequential([
                             tf.keras.layers.Dense(10, activation='relu'),
                             tf.keras.layers.Dense(10, activation='relu'),
                             tf.keras.layers.Dense(3)
])
model

In [25]:
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(X_train, Y_train, batch_size=50, epochs=100)

Epoch 1/100
33/33 [==============================] - 1s 2ms/step - loss: 14.1748 - accuracy: 0.8785
Epoch 2/100
33/33 [==============================] - 0s 1ms/step - loss: 14.1613 - accuracy: 0.8785
Epoch 3/100
33/33 [==============================] - 0s 1ms/step - loss: 14.1595 - accuracy: 0.8785
Epoch 4/100
33/33 [==============================] - 0s 1ms/step - loss: 14.1595 - accuracy: 0.8785
Epoch 5/100
33/33 [==============================] - 0s 1ms/step - loss: 14.1595 - accuracy: 0.8785
Epoch 6/100
33/33 [==============================] - 0s 1ms/step - loss: 14.1595 - accuracy: 0.8785
Epoch 7/100
33/33 [==============================] - 0s 1ms/step - loss: 14.1595 - accuracy: 0.8785
Epoch 8/100
33/33 [==============================] - 0s 1ms/step - loss: 14.1595 - accuracy: 0.8785
Epoch 9/100
33/33 [==============================] - 0s 1ms/step - loss: 14.1595 - accuracy: 0.8785
Epoch 10/100
33/33 [==============================] - 0s 1ms/step - loss: 14.1595 - accuracy: 0.8785

In [26]:
loss, accuracy = model.evaluate(X_test, Y_test, verbose=0)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

Test loss: 14.043488502502441
Test accuracy: 0.8712871074676514


In [27]:
Y_pred = model.predict(X_test)
Y_pred

13/13 [==============================] - 0s 1ms/step


array([[-53777.055, -54268.848,  54492.9  ],
       [-67773.6  , -68394.97 ,  68677.14 ],
       [-62720.098, -63294.535,  63555.746],
       ...,
       [-47499.902, -47935.56 ,  48133.277],
       [-62125.7  , -62694.113,  62952.918],
       [-48920.605, -49370.215,  49573.85 ]], dtype=float32)

In [28]:
actual = np.argmax(Y_test, axis=1)
predicted = np.argmax(Y_pred, axis=1)

print(f"actual: {actual}")
print(f"Predicted: {predicted}")

actual: [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 0 1 1 2 2
 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 0 2 2
 2 2 2 2 2 2 2 0 0 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 1 2 2 2 1 2 2 2 2 2 2 2 2
 2 2 0 2 2 2 0 2 2 2 2 2 2 1 2 2 2 2 0 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2
 2 2 1 2 2 2 2 2 2 2 2 2 1 1 2 1 2 0 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 1 2 2 1 2 2 2 2 1 2 2 2 2 2 2
 1 2 1 2 2 2 1 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 1 2 0 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2
 2 0 0 2 1 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 0 2 2 1 2 0 2 1 2 2
 2 1 2 2 2 2 1 2 2 2 2 0 2 1 2 2 2 2 2 2 2 1 2 2 2 0 2 2 2 2 2 2 2 2]
Predicted: [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 